mbari-org/SeafloorMappingDB

smdb/config/urls.py, smdb/scripts/load.py, smdb/smdb/admin.py, smdb/smdb/models.py, smdb/smdb/static/css/map.css, smdb/smdb/static/js/map.js, smdb/smdb/templates/base.html, smdb/smdb/templates/pages/home.html, smdb/smdb/views.py
Following excellent guidance from https://www.paulox.net/2020/12/08/maps-with-django-part-1-geodjango-spatialite-and-leaflet/
=> Get "Overview first"  map working on home page

README.md, smdb/scripts/load.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/6
=> Use locate(1) in load.py script to load Mission grid_bounds data

README.md, smdb/scripts/load.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/6
=> Documentation and load fixes

smdb/smdb/templates/admin/base_site.html
Per suggestion from: https://stackoverflow.com/a/64368855/1281657
=> Add favicon.ico to admin pages

.devcontainer/docker-compose.override.yml, smdb/compose/debug/django/Dockerfile, smdb/debug.yml
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/21
=> Fixups for VS Code debugging

smdb/config/api_router.py, smdb/smdb/api/serializers.py, smdb/smdb/api/views.py, smdb/smdb/conftest.py, smdb/smdb/tests/factories.py, smdb/smdb/tests/test_admin.py, smdb/smdb/tests/test_drf_urls.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/25
=> Add Person to the model test suite, hitting both DRF and admin interfaces

smdb/config/settings/base.py, smdb/config/urls.py, smdb/requirements/base.txt, smdb/smdb/schema.py, smdb/smdb/tests/snapshots/snap_test_graphql.py, smdb/smdb/tests/test_graphql.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/43
=> Use Snapshot testing to start writing tests for GraphQL

.vscode/launch.json, smdb/scripts/load.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/50
=> WIP: Handle edge cases of missing Notes and bad thumbnail files

.vscode/launch.json, smdb/compose/production/django/Dockerfile, smdb/scripts/load.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/50
=> Improve --mbsystem processing for working in production

smdb/config/settings/production.py, smdb/requirements/production.txt, smdb/scripts/load.py, smdb/smdb/utils/storages.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/57
=> Enable using AWS S3 for MEDIA file (thumbnail image) storing and serving

.vscode/launch.json, smdb/scripts/load.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/59
=> Pull out start_point and start_depth from mbinfo execution

smdb/scripts/load.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/59
=> Add Platform parsing from mission.comment

.vscode/launch.json, smdb/scripts/load.py, smdb/smdb/admin.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/59
=> Loader improvements: make sure thumbnail_image storage works, refactoring

smdb/config/urls.py, smdb/smdb/templates/base.html, smdb/smdb/templates/pages/home.html, smdb/smdb/templates/smdb/mission_detail.html, smdb/smdb/templates/smdb/mission_list.html, smdb/smdb/views.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/59
=> Updates to Overview first page

.vscode/launch.json, smdb/scripts/load.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/69
=> Fix edge cases for nav_track load

.vscode/launch.json, smdb/scripts/load.py, smdb/smdb/views.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/69
=> Show nav_track instead of grid_bounds on Overview First home page

.vscode/launch.json, smdb/config/urls.py, smdb/scripts/load.py, smdb/smdb/templates/smdb/expedition_detail.html, smdb/smdb/templates/smdb/expedition_list.html, smdb/smdb/templates/smdb/mission_detail.html, smdb/smdb/templates/smdb/mission_list.html, smdb/smdb/views.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/86
=> Add ExpeditionList and ExpeditionDetail Views - and link to Mission Views

smdb/scripts/load.py, smdb/smdb/templates/smdb/mission_detail.html, smdb/smdb/views.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/69
=> Preferentially load processed "*p.mb9[8-9]" .fnv files over unprocessed files

.vscode/launch.json
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/96
=> Add config for 2006 Mission that's not found in production

smdb/smdb/static/js/map.js, smdb/smdb/static/js/project.js, smdb/smdb/templates/pages/home.html, smdb/smdb/templates/smdb/expedition_list.html, smdb/smdb/templates/smdb/mission_list.html
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/96
=> Check for slug value so that all missions and expeditions are listed

smdb/config/exclude.list, smdb/smdb/static/js/map.js
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/96#issuecomment-948003350
=> Exclude mbsystem directory and show No_ZTopoSlopeNav_image.jpg in popup

smdb/smdb/static/css/project.css
Changed color of data marker color from blue (default) to a rust and increased stroke-width from 3 to 5.
=> Changed data marker color and stroke-width

smdb/notebooks/1.0-mpm-track_lengths.ipynb, smdb/scripts/load.py, smdb/smdb/templates/smdb/mission_detail.html
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/146
=> Store track_length in km

README.md, debug.yml, smdb/compose/debug/nginx/Dockerfile, smdb/compose/debug/nginx/nginx.conf, smdb/compose/production/traefik/Dockerfile, smdb/local.yml
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/76
=> Serve SeafloorMapping share files via HTTP with nginx in debug.yml and local.yml

README.md, smdb/compose/production/nginx/Dockerfile, smdb/compose/production/nginx/nginx.conf, smdb/compose/production/traefik/traefik.yml, smdb/compose/production/traefik/traefik_localhost.yml, smdb/production.yml, smdb/production_localhost.yml
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/76
=> Replace traefik with nginx so that it's easier to serve static files and SeafloorMapping

smdb/compose/debug/nginx/Dockerfile, smdb/smdb/templates/smdb/compilation_detail.html, smdb/smdb/templates/smdb/mission_detail.html, smdb/smdb/views.py
Applies https://github.com/mbari-org/SeafloorMappingDB/issues/76
=> Provide URL to to full rez thumbnail images

smdb/scripts/load.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/146
=> Pull total track lengths from .inf files and compare with haversine()

.vscode/launch.json, smdb/scripts/load.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/80
=> Look for both Figures.cmd and Figure.cmd files for Compilations

.vscode/launch.json, smdb/smdb/filters.py, smdb/smdb/models.py, smdb/smdb/tables.py, smdb/smdb/views.py
With django-tables and django-filter this is all that's needed to add a column!
=> Add thumbnail_filename column to compilations view

smdb/config/exclude.list, smdb/smdb/templates/pages/about.html
I added a few paths to exclude.list and fixed typos and grammar in my revision to About.html.  Please merge them with main. The "gerge ..." item in the pull request was added there but I don't know why, and the comment prompted by GitHub when I ran the "git push origin main" command of "merge ..." became "gerge ..." in vi with my clumsy typing trying to get out of there.
=> Updates to exclude.list and About.html

smdb/requirements/base.txt, smdb/requirements/local.txt, smdb/smdb/static/js/map.js, smdb/smdb/static/js/project.js, smdb/smdb/templates/pages/home.html
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/183
=> Undo revert back to pre-Dash PR front-end code

smdb/smdb/static/css/project.css, smdb/smdb/static/js/map.js, smdb/smdb/static/js/project.js, smdb/smdb/templates/base.html, smdb/smdb/templates/pages/about.html, smdb/smdb/templates/pages/home.html
Hi Mike,
Added text to about.html and created a footer on all pages stating that page content is for MBARI internal use only.
This was a request by Jenny.
=> About.html page updated and footer for all pages added

.vscode/launch.json, smdb/config/settings/base.py, smdb/scripts/load.py, smdb/scripts/survey_tally.py, smdb/smdb/tables.py
=> Test round-tripping of .xlsx -> db -> .csv -> .xlsx -> db

smdb/scripts/survey_tally.py
=> Skip over .xlsx files not found

.vscode/launch.json, smdb/scripts/survey_tally.py
=> Add --last_n_days option to survey_tally.py

.vscode/launch.json, smdb/scripts/load.py, smdb/scripts/survey_tally.py
=> Fix --last_n_days for SurveyTally exection from load.py

smdb/smdb/static/css/map_mission_filter.css
=> Github Issue #72: Enhance Mission Detail View - Update#2

smdb/smdb/templates/base.html
=> Github Issue #72: Enhance Missions Detail View - Update#2

smdb/smdb/templates/base.html
Fixing an overwrite of Mike's changes today downgrading Bootstrap to 4.
=> Fixing an overwrite of Mike's changes today downgrading Bootstrap to 4.

smdb/smdb/templates/base.html
Reverts mbari-org/SeafloorMappingDB#219
=> Revert "Fixing an overwrite of Mike's changes today downgrading Bootstrap to 4."

smdb/smdb/templates/base.html
Reverts mbari-org/SeafloorMappingDB#217
Hoping this fixes problem seen in https://github.com/mbari-org/SeafloorMappingDB/pull/221#issuecomment-2123499467
=> Revert "Github Issue #72: Enhance Missions Detail View - Update#2"

smdb/smdb/tables.py
=> Hyperlink to new tab the mgds_compilation

smdb/smdb/static/js/map_mission_filter.js
=> Add 'Route: <route_file>' to popup on missions page

.vscode/launch.json, smdb/config/exclude.list, smdb/scripts/load.py, smdb/scripts/survey_tally.py, smdb/smdb/filters.py, smdb/smdb/forms.py, smdb/smdb/templates/smdb/compilation_filter.html, smdb/smdb/templates/smdb/expedition_filter.html, smdb/smdb/views.py
=> Use crispy forms for expeditions and compilations, --spreadsheet loading fixes

smdb/scripts/load.py, smdb/smdb/templates/smdb_tables2_bootstrap5.html
=> Fix problems seen after last night's load, copy in smdb_tables2_bootstrap5.html in case we need it

smdb/scripts/load.py
=> Remove any commas in the csv fields, clean up logger output

smdb/scripts/load.py
=> Log appropriate counts for .xlsx -> db -> .csv

.vscode/launch.json, smdb/scripts/load.py
=> Allow 'yes' for Patch_test and Repeat_survey, more error trapping

smdb/smdb/admin.py, smdb/smdb/filters.py
=> Fixes for missions: admin interface fix, filtering widget improvements

.vscode/launch.json, smdb/scripts/load.py, smdb/smdb/templates/smdb_tables2_bootstrap5.html
=> Allow Mission in .xlsx to include the parent directory or not

smdb/smdb/static/css/project.css, smdb/smdb/templates/smdb/mission_detail.html
Apples to https://github.com/mbari-org/SeafloorMappingDB/issues/206
=> Add new fields to the Mission details page

smdb/scripts/load.py, smdb/smdb/views.py
=> Fix ordering

smdb/smdb/filters.py
This solves the problem seen when creating a new database from scratch following the [README.md instructions](https://github.com/mbari-org/SeafloorMappingDB/blob/ceac6548a8ef0f3f2e981068a3d8045aaa81efd6/README.md):
```
django        |   File "/app/smdb/config/urls.py", line 12, in <module>
django        |     from smdb.views import (
django        |   File "/app/smdb/smdb/views.py", line 22, in <module>
django        |     from smdb.filters import CompilationFilter, ExpeditionFilter, MissionFilter
django        |   File "/app/smdb/smdb/filters.py", line 13, in <module>
django        |     class MissionFilter(FilterSet):
django        |   File "/app/smdb/smdb/filters.py", line 22, in MissionFilter
django        |     choices=[
django        |   File …
```
=> Catch ProgrammingError from ChoiceFilter() during inital migrate command

smdb/smdb/views.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/72
=> Order Missions, Expeditions, and Compilations by name in the table views

smdb/smdb/tables.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/72
=> Add vehicle_name and quality_comment to the MissionTable view

.vscode/launch.json, smdb/scripts/load.py
Applies to https://github.com/mbari-org/SeafloorMappingDB/issues/249
=> Write consolidated exclude_list.txt file in same place as load log file

smdb/smdb/static/css/filters.css, smdb/smdb/static/css/leaflet-measure.css, smdb/smdb/static/css/map.css, smdb/smdb/static/css/map_compilation_filter.css, smdb/smdb/static/css/map_expedition_filter.css, smdb/smdb/static/css/map_mission_filter.css, smdb/smdb/static/css/navbar-nav.css, smdb/smdb/static/css/project.css, smdb/smdb/static/js/SliderControl.js, smdb/smdb/templates/base.html, smdb/smdb/templates/smdb/compilation_filter.html, smdb/smdb/templates/smdb/expedition_filter.html, smdb/smdb/templates/smdb/mission_filter.html, smdb/smdb/templates/smdb_tables2_bootstrap4.html
This commit addresses Issue #255 "https://github.com/mbari-org/SeafloorMappingDB/issues/255"
Creating new .CSS files for the navigation, filter row and updating map views. This requires moving non-project (especially non-backend) specific css code from project.css into these new files. These changes are based on the last SMDB meeting with Mike M. and Jenny P. This also requires updates to base.html in order to add these new .css files to the project.
=> Adding several new CSS files for the SMDB UI so that they are separate from project.css. #255

smdb/smdb/static/css/filters.css
This update solves various aspects of the Responsive View problem on desktop. Will need to re-address further when shifting to other media views (phone, iPads).
=> Need to fix the Responsive View of the Mission Page's Filter and Clear Buttons. #267 - 

smdb/smdb/forms.py
- Clear button on each Data Filter now reloads the page in order to clear previously submitted input and text.
=> The Clear Button does not work on the SMDB Data Filter Forms #269
